// netease-react/src/views/toplist.js
import React,{Component} from 'react'
import '../static/css/home.css'
import { WingBlank,Grid, Toast,NavBar,Icon as MIcon} from 'antd-mobile';
import {Skeleton} from 'antd';
import {connect} from 'react-redux';
import {changeActive,changeMp3,changePic} from '../store/actions';
import axios from 'axios';
import {Link,withRouter} from 'react-router-dom';
import { LazyLoadImage } from 'react-lazy-load-image-component';
import {PullToRefresh} from 'react-weui';
const lazy = '/favicon.ico';

function mapStateToProps(state){
    return {
        count: state.reducer.active,
        api: state.reducer.api,
        mp3: state.reducer.mp3
    }
}

function mapActionToProps(dispatch){
    return {
        changeView: (num)=>{dispatch(changeActive(num))},
        changeMp3: (url)=>{dispatch(changeMp3(url))},
        changePic: (pic)=>{dispatch(changePic(pic))}
    }
}

class TopList extends Component {

    constructor(){
        super();
        this.state = {
            topList: [],
            loading: true
        }
    }

    componentWillMount(){
        this.loadTopList();
    }

    loadTopList = (resolve) => {
        this.setState({
            loading: true
        })
        axios({
            url: `${this.props.api}/toplist/detail`,
            timeout: 15000
        }).then(res=>{
            if(res.status == 200){
                this.setState({
                    topList: res.data.list,
                    loading: false
                })
                if(resolve){
                    resolve();
                }
            }
        }).catch(err=>{
            // console.log(err)
            Toast.fail('网络请求超时', 1);
            this.setState({
                loading: true
            })
            if(resolve){
                resolve();
            }
        })
    }

    render() {
        return (
                <div className="app-album">
                    <div className="cmt-bar" style={{background:'#fff',zIndex:100}}>
                        <NavBar
                            mode="light"
                            icon={<MIcon type="left" />}
                            onLeftClick={() => {this.props.history.go(-1)}}
                        >
                            <h3 className="" style={{margin: 0}}>Toplist</h3>
                        </NavBar>
                    </div>
                    <PullToRefresh
                        onRefresh={
                            resolve => {
                                this.loadTopList(resolve)
                            }
                        }
                    >
                    <WingBlank>
                        <Skeleton loading={this.state.loading} active avatar paragraph={{ rows: 7 }}>
                    <div className="top-content">
                        <h3>官方榜</h3>
                        {
                            this.state.topList.slice(0,4).map((item,i)=>{
                                return (
                                    <Link to={`/playlist/${item.id}`} className="top-block" key={`tp${i}`}>
                                        <div className="toplist">
                                            <div className="top-cover">
                                                {/* <img src={item.coverImgUrl} /> */}
                                                <LazyLoadImage
                                                    src={item.coverImgUrl} 
                                                    placeholderSrc={lazy}
                                                    width={'100%'}
                                                    height={'100%'}
                                                />
                                                <p className="top-update">{item.updateFrequency}</p>
                                            </div>
                                            <div className="top-track">
                                                {
                                                    item.tracks.map((obj,i)=>{
                                                        return (
                                                            <p key={item.name+i}>
                                                                {i+1}.{obj.first}-{obj.second}
                                                            </p>
                                                        )
                                                    })
                                                }
                                            </div>
                                        </div>
                                    </Link>
                                )
                            })
                        }
                    </div>
                    <div className="top-content">
                        <h3>推荐榜</h3>
                        <Grid data={this.state.topList.slice(4,10)} hasLine={false} activeStyle={false} columnNum={3}
                            square={false}
                            renderItem={dataItem => (
                                <Link to={`/playlist/${dataItem.id}`} style={{ padding: '4px',position:'relative',display:'block' }}>
                                    <LazyLoadImage
                                        src={dataItem.coverImgUrl} 
                                        placeholderSrc={lazy}
                                        height="100"
                                        width="100%"
                                    />
                                    <div style={{ color: '#888', fontSize: '12px', marginTop: '0px' }}>
                                        <span className="grid-title">{dataItem.name}</span>
                                    </div>
                                    <span style={{position:'absolute',top: '5px',right:'10px',color:'#fff',fontSize:12}}>
                                        {dataItem.updateFrequency}
                                    </span>
                                </Link>
                            )}
                        />
                    </div>

                    <div className="top-content">
                        <h3>全球榜</h3>
                        <Grid data={this.state.topList.slice(10,16)} hasLine={false} activeStyle={false} columnNum={3}
                            square={false}
                            renderItem={dataItem => (
                                <Link to={`/playlist/${dataItem.id}`} style={{ padding: '4px',position:'relative',display:'block' }}>
                                    <LazyLoadImage
                                        src={dataItem.coverImgUrl} 
                                        placeholderSrc={lazy}
                                        height="100"
                                        width="100%"
                                    />
                                    <div style={{ color: '#888', fontSize: '12px', marginTop: '0px' }}>
                                        <span className="grid-title">{dataItem.name}</span>
                                    </div>
                                    <span style={{position:'absolute',top: '5px',right:'10px',color:'#fff',fontSize:12}}>
                                        {dataItem.updateFrequency}
                                    </span>
                                </Link>
                            )}
                        />
                    </div>
                    <div className="top-content">
                        <h3>更多榜单</h3>
                        <Grid data={this.state.topList.slice(16,)} hasLine={false} activeStyle={false} columnNum={3}
                            square={false}
                            renderItem={dataItem => (
                                <Link to={`/playlist/${dataItem.id}`} style={{ padding: '4px',position:'relative',display:'block' }}>
                                    <LazyLoadImage
                                        src={dataItem.coverImgUrl} 
                                        placeholderSrc={lazy}
                                        height="100"
                                        width="100%"
                                    />
                                    <div style={{ color: '#888', fontSize: '12px', marginTop: '0px' }}>
                                        <span className="grid-title">{dataItem.name}</span>
                                    </div>
                                    <span style={{position:'absolute',top: '5px',right:'10px',color:'#fff',fontSize:12}}>
                                        {dataItem.updateFrequency}
                                    </span>
                                </Link>
                            )}
                        />
                    </div>
                    </Skeleton>
                    </WingBlank>
                    </PullToRefresh>

                </div>

        )
    }
}

export default withRouter(connect(mapStateToProps,mapActionToProps)(TopList));

// netease/src/views/toplist.vue
<template>
    <div>
        <Head :child="true">
            <span slot="hname">迪爷排行榜</span>
        </Head>
        <div class="toplist">
            <div v-for="item of topLists.slice(0,1)" :key="'top'+item.id">
                <h3 class="top_title">{{item.name}}</h3>
                <div>
                    <router-link :to="'/pylist/'+item.id" class="flex listitem">
                        <div class="itemcover">
                            <!-- <van-image lazy-load width="120" height="120" :src="item.coverImgUrl"></van-image> -->
                            <img v-lazy="item.coverImgUrl" style="width:110px">
                            <span class="msk">{{item.updateFrequency}}</span>
                        </div>
                        <div class="listtrack">
                            <p class="elp" v-for="(obj,i) of item.tracks">{{i+1+' '}}{{obj.first+'-'+obj.second}}</p>
                        </div>
                    </router-link>
                </div>
            </div>

            <div>
                <h3 class="top_title">官方榜</h3>
                <div v-for="item of topLists.slice(1,7)" :key="'top'+item.id">
                    <router-link :to="'/pylist/'+item.id" class="flex listitem">
                        <div class="itemcover">
                            <!-- <van-image lazy-load width="120" height="120" :src="item.coverImgUrl"></van-image> -->
                            <img v-lazy="item.coverImgUrl" style="width:110px">
                            <span class="msk">{{item.updateFrequency}}</span>
                        </div>
                        <div class="listtrack">
                            <p class="elp" v-for="(obj,i) of item.tracks">{{i+1+' '}}{{obj.first+'-'+obj.second}}</p>
                        </div>
                    </router-link>
                </div>
            </div>

            <div>
                <h3 class="top_title">推荐榜</h3>
                <van-grid :column-num="3" :center="false">
                    <van-grid-item v-for="item of topLists.slice(7,13)" :key="'top'+item.id" :to="'/pylist/'+item.id">
                        <div class="itemcover">
                            <!-- <van-image lazy-load :src="item.coverImgUrl"></van-image> -->
                            <img v-lazy="item.coverImgUrl" width="90">
                            <span class="msk">{{item.updateFrequency}}</span>
                        </div>
                        <p class="itemname">{{item.name}}</p>
                    </van-grid-item>
                </van-grid>
            </div>

            <div>
                <h3 class="top_title">全球榜</h3>
                <van-grid :column-num="3" :center="false">
                    <van-grid-item v-for="item of topLists.slice(13,19)" :key="'top'+item.id" :to="'/pylist/'+item.id">
                        <div class="itemcover">
                            <!-- <van-image lazy-load :src="item.coverImgUrl"></van-image> -->
                            <img v-lazy="item.coverImgUrl">
                            <span class="msk">{{item.updateFrequency}}</span>
                        </div>
                        <p class="itemname">{{item.name}}</p>
                    </van-grid-item>
                </van-grid>
            </div>

            <div>
                <h3 class="top_title">更多榜单</h3>
                <van-grid :column-num="3" :center="false">
                    <van-grid-item v-for="item of topLists.slice(19)" :key="'top'+item.id" :to="'/pylist/'+item.id">
                        <div class="itemcover">
                            <!-- <van-image lazy-load :src="item.coverImgUrl"></van-image> -->
                            <img v-lazy="item.coverImgUrl">
                            <span class="msk">{{item.updateFrequency}}</span>
                        </div>
                        <p class="itemname">{{item.name}}</p>
                    </van-grid-item>
                </van-grid>
            </div>
        </div>
        <p class="text-center" v-show="error" style="margin-top: 20px;">
            <van-button type="info" @click="loadTopList">重启加载</van-button>
        </p>
        <Masks :loadover="loadover" />
    </div>
</template>
<script>
import {mapActions,mapGetters} from 'vuex';
import axios from 'axios';
import Vue from 'vue';
import Head from '../components/head';
import Masks from '../components/mask';
import { Swipe,SwipeItem,Toast,Grid,GridItem,Image,Icon,List,Button,Search,Tab,Tabs} from 'vant';

Vue.use(Swipe)
    .use(SwipeItem)
    .use(Toast)
    .use(Grid)
    .use(GridItem)
    .use(Image)
    .use(Icon)
    .use(List)
    .use(Button)
    .use(Search)
    .use(Tab)
    .use(Tabs);
export default {
    name: 'TopList',
    data(){
        return{
            topLists: [],
            loadover: false,
            error: false
        }
    },
    created(){
        this.loadTopList();
    },
    computed: {
        ...mapGetters(['getMyApi'])
    },
    methods: {
        loadTopList(){
            this.loadover = false;
            this.loadover = false;
            axios({
                method: 'get',
                url: `${this.getMyApi}/toplist/detail`,
                timeout: 15000
            }).then(res=>{
                // console.log(res);
                this.loadover = true;
                if(res.data.code == 200){
                    this.topLists = res.data.list;
                    this.error = false;
                }else{
                    this.error = true;
                    Toast.fail('网络请求错误');
                }
            }).catch(err=>{
                this.error = true;
                this.loadover = true;
                Toast.fail('网络请求错误');
            })
        }
    },
    components: {Head,Masks}
}
</script>
<style scoped>
    .toplist{
        margin: 50px 0;
        padding: 0 10px;
    }
    .top_title{
        color: #000;
        line-height: 3em;
        font-weight: bold;
    }
    .listitem{
        justify-content: space-between;
        align-items: center;
        width: 100%;
    }
    .listtrack{
        flex: 1;
        margin-left: 10px;
        color: #999;
        overflow: hidden;
    }
    .listtrack p{
        line-height: 2em;
    }
    .itemcover{
        position: relative;
        overflow: hidden;
        background: url(../../static/img/blank.png) no-repeat;
        background-size: contain;
        background-position: center;
    }
    .itemcover>img{
        width: 100%;
    }
    .msk{
        position: absolute;
        bottom: 4px;
        left: 0;
        width: 100%;
        height: 30px;
        background: linear-gradient(to top,rgba(0,0,0,.3),rgba(0,0,0,.01));
        display: block;
        color: #eee;
        font-size: 12px;
        line-height: 30px;
        text-indent: 1em;
    }
    .itemname{
        overflow: hidden;
        text-overflow:ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 1;
        -webkit-box-orient: vertical;
    }
</style>
